

services:
    unifik_database_config.repositories.extension:
        class: Doctrine\ORM\EntityRepository
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository
        arguments:
            - Unifik\DatabaseConfigBundle\Entity\Extension

    unifik_database_config.services.configuration:
        class: Unifik\DatabaseConfigBundle\Service\ConfigurationService
        arguments: [ "@kernel", "@unifik_database_config.repositories.extension" ]