parameters:
    unifik_database_config.container_invalidator.class: Unifik\DatabaseConfigBundle\Lib\ContainerInvalidator

services:
    unifik_database_config.container_invalidator:
        class: %unifik_database_config.container_invalidator.class%
        arguments: [ "@kernel" ]
